

import {ProDash} from "../../../components/ProsArea/ProDashboard/ProfileDashboard";





export const metadata = {
  title: "Pros Overview | Profer",
  description: "Generated by create next app",
};




export default function ProProfile() {
  return (
    <>
     
     <ProDash></ProDash>
    </>
  );
}
