

import {ProDash} from "../../../components/ProsArea/ProDashboard/ProfileDashboard";

import {UpgradeModal} from "../../../components/ProsArea/PaymentModal/PaymentModal";



export const metadata = {
  title: "Pros Overview | Profer",
  description: "Generated by create next app",
};




export default function ProProfile() {
  return (
    <>
     <UpgradeModal></UpgradeModal>
     <ProDash></ProDash>
    </>
  );
}
