
import {EmailProVerify} from "../../components/Frontend/EmailVerifyPage/EmailProVerify";


export const metadata = {
  title: "Pro Email Verify | Profer",
  description: "Generated by create next app",
};





export default function Page() {
  return (
   <>
   

    <EmailProVerify />
   
   </>
);
}