import { LoginAdminFrontend } from "@/components/Areas/shared/LoginAdmin";
import { Metadata } from "next";





export const metadata: Metadata = {
  title: "Admin Login | Profer",
  description: "Generated by create next app",
};




export default function AdminLoginPage() {

    return(<>

     <LoginAdminFrontend></LoginAdminFrontend>
   
    
    </>);
}