import ContactUs from '@/components/Frontend/ContactUs/ContactUs'

export const metadata = {
  title: "Contact | Profer",
  description: "Generated by create next app",
};







export default function Privacy1() {
  return (
    <>
      <ContactUs />
    </>
  );
}
