import { Whyprofer } from "@/components/Frontend/Whyprofer/Whyprofer";
import { Metadata } from "next";




export const metadata: Metadata = {
  title: "Why Profer | Profer",
  description: "Generated by create next app",
};




export default function Page(){

    return(<>
    
    <Whyprofer></Whyprofer>
    
    
    </>);
}