import { BusinessDetails } from "../../../components/ProsArea/BusinessDetails/ProBusinessDetails";
import {UpgradeModal} from "../../../components/ProsArea/PaymentModal/PaymentModal";




export const metadata = {
  title: "Pros Business | Profer",
  description: "Generated by create next app",
};


export default function Page(){


    return(<>
     <UpgradeModal />
        <BusinessDetails></BusinessDetails>
    </>);
}