import { ProDashBoardHero } from "../../../components/ProsArea/shared/ProDashBoardCard";





export const metadata = {
  title: "Pros DashBoard | Profer",
  description: "Generated by create next app",
};




export default function Page(){

    

    return(<>

      <ProDashBoardHero></ProDashBoardHero>
    








    </>);
}