import { ProDash } from "../../../components/ProsArea/ProDash/ProsDashboard";
import { ProDashBoardHero } from "../../../components/ProsArea/shared/ProDashBoardCard";
import {UpgradeModal} from "../../../components/ProsArea/PaymentModal/PaymentModal";




export const metadata = {
  title: "Pros DashBoard | Profer",
  description: "Generated by create next app",
};




export default function Page(){

    

    return(<>

        <UpgradeModal />
      <ProDash></ProDash>
    
    </>);
}