import { ProsStep } from "../../../../components/ProsArea/Prossteps/ProsStep1";





export const metadata = {
  title: "Pros Step 1 | Profer",
  description: "Generated by create next app",
};

export default function Page(){

    return(<>
       
        <ProsStep></ProsStep>

    
    </>);
}