import SignIn from "@/components/Frontend/Signin/Signinfrontend";





export const metadata = {
  title: "Sign in | Profer",
  description: "Generated by create next app",
};




export default function Paged(){

    return(<>

       <SignIn></SignIn>
    </>);
}