
import {ProCredential} from "../../../components/ProsArea/ProCredentials/ProCredentialList";


export const metadata = {
  title: "Pros Credentials | Profer",
  description: "Generated by create next app",
};



export default function Page() {
 



  return(<>
    <ProCredential></ProCredential>
  
  </>);
}
