import { SearchForPros } from "@/components/Frontend/Searchforpros/Searchforpros";
import { Metadata } from "next";






export const metadata: Metadata = {
  title: "Search For Pros | Profer",
  description: "Generated by create next app",
};


export default function SearchFor(){


    return(<>
       
       <SearchForPros></SearchForPros>
    
    </>);
}