import { ProUpdate } from "../../../components/ProsArea/ProUpdate/ProfileUpdate";




export const metadata = {
  title: "Pros Update | Profer",
  description: "Generated by create next app",
};



export default function page(){


    return(<>

        <ProUpdate></ProUpdate>


    
    </>);
}