import { PreferTime } from "../../../components/Areas/PreferedTimeProjectRequested/Prefer";



export const metadata = {
  title: "Prefered Time | Profer",
  description: "Generated by create next app",
};



export default function Page(){

    return(<>
    
        <PreferTime></PreferTime>
    </>);
}