import { ProSubscription } from "../../../components/ProsArea/ProSubscription/SubscriptionInfo";




export const metadata = {
  title: "Pros Subscription | Profer",
  description: "Generated by create next app",
};



export default function page(){


    return(<>

        <ProSubscription></ProSubscription>


    
    </>);
}