
import { stripe } from "../../lib/stripe";
import {Companyprofile} from "../../components/Frontend/ProsStepOne/ProsFirstStep";

export const metadata = {
  title: "Pros Company | Profer",
  description: "Generated by create next app",
};



export default async function Comapnyprofile({ searchParams }) {

 const { payment_intent: paymentIntentId } = searchParams;
  
  

  return (
     <>
      {/* <h2>Payment {paymentIntent.status}</h2>
      <p>Payment ID: {paymentIntent.id}</p>  */}
      <Companyprofile paymentIntentId ={paymentIntentId}></Companyprofile>
     </>
    
  );
}

