
export const dynamic = 'force-dynamic';
import { stripe } from "../../lib/stripe";
import {Companyprofile} from "../../components/Frontend/ProsStepOne/ProsFirstStep";

export const metadata = {
  title: "Pros Company | Profer",
  description: "Generated by create next app",
};



export default async function Comapnyprofile({ searchParams }) {

 const { paymentIntentId } = searchParams;
  
  
 

  return (
     <>
      
      <Companyprofile paymentIntentId ={paymentIntentId}></Companyprofile>
     </>
    
  );
}

