import ForgotPassword from "../../components/Frontend/Signin/Forgotpassword";







export const metadata = {
  title: "Forgot Password | Profer",
  description: "Generated by create next app",
};




export default function Page(){


    return(<>
      <ForgotPassword></ForgotPassword>

    </>);
}