
export const dynamic = 'force-dynamic';
import {ProsCheckout} from "../../components/Frontend/ProPayment/MembershipPayment.jsx";


export const metadata = {
  title: "Checkout | Profer",
  description: "Generated by create next app",
};




export default function Page(){


   const calculateOrderAmount =  300; // Replace with real calculation
  

  return(<>
  
    <ProsCheckout />

  </>);
}