
import { Header } from "@/components/Frontend/shared/Header";
import Home from "../components/Frontend/homepagecomponents/Homepage";import { Footer } from "@/components/Frontend/shared/Footer";
;


export const metadata = {
  title: "Home | Profer",
  description: "Generated by create next app",
};






export default function Page() {
  return (
  <>



       <Home></Home>


  </>
  );
}