
import { UpgradeModal } from "@/components/ProsArea/PaymentModal/PaymentModal";
import ProsStepNextCredentials from "../../../../components/ProsArea/Prossteps/ProsthirdStep";





export const metadata = {
  title: "Pros Step 3 | Profer",
  description: "Generated by create next app",
};




export default function Page(){

    return(<>
       
      <UpgradeModal></UpgradeModal>
      <ProsStepNextCredentials></ProsStepNextCredentials>

    </>);
}