import Termsconditions from '@/components/Frontend/Termsconditions/Termsconditions'


export const metadata = {
  title: "Terms & Privacy | Profer",
  description: "Generated by create next app",
};




export default function Privacy1() {
  return (
    <>
      <Termsconditions />
    </>
  );
}
