
import Image from "next/image";


export const metadata = {
  title: "How it Works | Profer",
  description: "Generated by create next app",
};




export default function Howitworks() {
  return (
    <>
      {/* Hero Section */}
      <section className="bg-white py-12 sm:py-16 relative overflow-hidden">
        <div className="relative z-10 max-w-4xl mx-auto text-center px-4 sm:px-6">
          <h1 className="text-4xl sm:text-6xl font-semibold text-gray-900 mb-4">
            Pro right ahead.
          </h1>
          <p className="text-xl sm:text-2xl text-gray-500 mb-8 leading-relaxed">
            Your next project starts with<br /> these easy steps.
          </p>
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-white py-12 sm:py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 space-y-12 sm:space-y-16">

          {/* Feature 1 */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
            <div className="text-center md:text-left flex flex-col justify-center">
              <h3 className="text-3xl sm:text-4xl md:text-5xl font-semibold mb-2 sm:mb-3">
                Find the pros for you
              </h3>
              <p className="text-lg sm:text-xl md:text-2xl text-gray-600 leading-relaxed">
                Search and verify your Pro before ever starting a project.  
                Make sure they are legit.
              </p>
            </div>
            <div className="flex justify-center md:justify-center mt-4 md:mt-0">
              <Image 
                src="/images/p4.png" 
                alt="Chat icon" 
                width={350} 
                height={200} 
                className="rounded-lg"
              />
            </div>
          </div>

          {/* Feature 2 */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
            <div className="flex justify-center md:justify-center mt-4 md:mt-0">
              <Image 
                src="/images/p5.png" 
                alt="Save icon" 
                width={350} 
                height={200} 
                className="rounded-lg"
              />
            </div>
            <div className="text-center md:text-left flex flex-col justify-center mt-4 md:mt-0">
              <h3 className="text-3xl sm:text-4xl md:text-5xl font-semibold mb-2 sm:mb-3">
                Save your favorite pros
              </h3>
              <p className="text-lg sm:text-xl md:text-2xl text-gray-600 leading-relaxed">
                Finding and saving your favorite Pros has never been easier.  
                With one click, keep your go-to Pros close.
              </p>
            </div>
          </div>

          {/* Feature 3 */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-center">
            <div className="text-center md:text-left flex flex-col justify-center">
              <h3 className="text-3xl sm:text-4xl md:text-5xl font-semibold mb-2 sm:mb-3">
                Share a pro, reap the rewards.
              </h3>
              <p className="text-lg sm:text-xl md:text-2xl text-gray-600 leading-relaxed">
                Get reward points when you refer your fav Pro to someone new. Then apply your points to save money on your projects at the  
                <span className="text-black font-bold">
                  Project<span className="text-red-500">Auction</span>™
                </span>.
              </p>
            </div>
            <div className="flex justify-center md:justify-center mt-4 md:mt-0">
              <Image 
                src="/images/p6.png" 
                alt="Reward icon" 
                width={350} 
                height={250} 
                className="rounded-lg"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Project Auction Section */}
      <section className="bg-white py-12 sm:py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 grid grid-cols-1 md:grid-cols-2 gap-8 items-center">

          {/* Image */}
          <div className="flex justify-center md:justify-start mt-4 md:mt-0">
            <Image 
              src="/images/p3.png" 
              alt="Project Auction"
              width={450}
              height={300}
              className="rounded-lg"
            />
          </div>

          {/* Text */}
          <div className="text-center md:text-left max-w-5xl mx-auto px-4 mt-6 md:mt-0">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              Project <span className="text-red-500">Auction</span>™
            </h2>
   <p className="text-base sm:text-lg md:text-xl lg:text-2xl text-gray-500 leading-relaxed text-justify">Submit your project and deposit $100, which is applied to the project.
     We'll create a <span className="font-bold text-black">Job<span className="text-red-500">File</span>™</span> with a finalized scope of work that you sign off on. Your project then enters our Project Auction™ where Pros bid and compete for your business. Once the bidding closes, you choose from the three lowest qualified bids.</p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <div className="bg-[#b6e3e9] py-12 sm:py-16 px-4 sm:px-6 text-center">
        <div className="flex flex-col items-center space-y-6 sm:space-y-8">
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-semibold">
            Start your next search for <span className="text-red-500">free</span> today.
          </h2>

          <div className="flex justify-center md:justify-start mt-4 md:mt-0">
            <Image 
              src="/images/9.png" 
              alt="Project Auction"
              width={300} 
              height={200} 
              className="rounded-lg"
            />
          </div>

          <a
            href="#"
            className="inline-block bg-red-500 text-2xl sm:text-3xl px-6 sm:px-8 py-3 sm:py-4 rounded-full shadow-md hover:bg-red-600 transition duration-300 min-w-[180px] sm:min-w-[220px] text-center mt-4 text-white">
            Get Started
          </a>
        </div>
      </div>
    </>
  );
}
