
import { Metadata } from "next";




export const metadata: Metadata = {
  title: "Permission Role | Profer",
  description: "Generated by create next app",
};


export default function Page() {
  return (
   <>
     
   </>);
}