import { AdminDashboard } from "@/components/Areas/Dashboard/AdminDashboard";
import { Metadata } from "next";






export const metadata: Metadata = {
  title: "Dashboard | Profer",
  description: "Generated by create next app",
};




export default function DashboardPage() {
  return (

    
    <AdminDashboard></AdminDashboard>



  );
}