import { AdminForgotPassword } from "@/components/Areas/shared/AdminForgotPassword";
import { Metadata } from "next";




export const metadata: Metadata = {
  title: "Admin Forgot Password | Profer",
  description: "Generated by create next app",
};



export default function PageForgotPassword(){

    return (
        <>
           <AdminForgotPassword />
        </>
    );
}