import {SelectProPlan} from "../../components/Frontend/Selectplan/SelectProPlan";

export const metadata = {
  title: "Join Profer | Profer",
  description: "Generated by create next app",
};



export default function ProPlan() {
  
   

  return (
   <>
   <SelectProPlan></SelectProPlan>
   

   
   </>
  );
}
