

import { Bid } from "../../../components/ProsArea/BidManagement/BidManagementList";
import {UpgradeModal} from "../../../components/ProsArea/PaymentModal/PaymentModal";


export const metadata = {
  title: "Pros Bid | Profer",
  description: "Generated by create next app",
};


export default function Home() {
  

  return (
    <>
      <UpgradeModal></UpgradeModal>
    
      <Bid></Bid>
      
    </>
  );
}

