import { Subscriptions } from "../../../components/ProsArea/SubscriptionDetails/Subscription";






export const metadata = {
  title: "Pros Subscription | Profer",
  description: "Generated by create next app",
};




export default function Page(){


    return(<>

        <Subscriptions></Subscriptions>
    </>);
}