import { MakeBids } from "../../../../components/ProsArea/Makebidmanagement/MakeBid";




export const metadata = {
  title: "Make Bid | Profer",
  description: "Generated by create next app",
};



export default function Page({params}){


  const { id } = params;


    return(<>
      <MakeBids projectid = {id}></MakeBids>
    
    </>);
}