
import Image from "next/image";
import Link from "next/link";







export const metadata = {
  title: "Profer Network | Profer",
  description: "Generated by create next app",
};




export default function Profernetwork() {
  return (
    <>
      {/* First Section */}
      <section className="flex flex-col md:flex-row items-center justify-between max-w-6xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
        {/* Left Heading */}
        <div className="flex-1 text-center md:text-left mb-6 md:mb-0">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold tracking-tight">
            Way to go, <span className="text-black">Pro.</span>
          </h1>
        </div>

        {/* Right Content */}
        <div className="flex-1 text-center md:text-left">
          <p className="text-base sm:text-lg font-medium text-gray-900">
            As an experienced service professional, you do things right. So let it show.
          </p>
          <p className="mt-3 text-gray-500 text-sm sm:text-base mb-10">
            Profer is the first and only network that truly lets your caliber
            shine through to your clients.
          </p>

          <Link href="/select-plan" className = "mt-10 px-5 sm:px-6 py-2 bg-red-500 hover:bg-red-600 text-white font-medium rounded-full transition duration-300">
            Choose Your Plan
          </Link>
          
        </div>
      </section>

      {/* Image Section */}
      <div className="mt-6 sm:mt-8 flex flex-col items-center gap-4 sm:gap-6 px-4">
        <Image
          src="/images/p1.png"
          alt="Professional reviewing credentials"
          width={850}
          height={350}
          className="object-contain w-full max-w-4xl h-auto"
          priority
        />
      </div>

      {/* Build Profile Section */}
  <section className="bg-[#b6e3e9] py-10 sm:py-12 px-4">
  <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 md:gap-10">
    {/* Left Text */}
   <h1 className="text-4xl sm:text-3xl md:text-4xl font-semibold text-center md:text-left md:ml-30">
  Build your{" "}
  <span className="text-black font-bold">
    Pro<span className="text-red-500">File</span>™
  </span>
</h1>


    {/* Right Content */}
    <div className="max-w-lg text-center md:text-left md:pl-4">
      <p className="text-gray-800 text-base sm:text-lg md:text-2xl leading-relaxed">
        Your{" "}
        <span className="text-black font-bold">
          Pro<span className="text-red-500">File</span>™
        </span>{" "}
        page is the best trust mark for your potential clients. Manage your
        licensing and credentials all in one place. Prove you’re a real pro.
      </p>
      <a
        href="#"
        className="mt-4 inline-flex items-center gap-1 sm:gap-2 text-[#00a6a6] text-base sm:text-lg md:text-xl font-semibold hover:underline"
      >
        <span className="text-xl sm:text-2xl">→</span> View example ProFile™
      </a>
    </div>
  </div>
</section>



      {/* Section with Image Left */}
     <div className="mt-8 flex flex-col md:flex-row items-center md:items-start gap-8 py-8 px-4">
  <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center md:items-start gap-8">
    {/* Left Side - Image */}
    <div className="flex-shrink-0 w-full md:w-auto flex justify-center md:justify-start">
      <Image
        src="/images/p2.png"
        alt="Professional reviewing credentials"
        width={550}
        height={250}
        className="object-contain"
        priority
      />
    </div>

    {/* Right Side - Text */}
    <div className="flex-1 max-w-xl text-center md:text-left">
      <h2 className="text-3xl sm:text-4xl font-semibold mb-4">Let your Pro show</h2>

      <p className="text-gray-700 mb-4 text-lg sm:text-xl">
        <strong className="font-semibold text-black">Host and manage your Pro credentials</strong> like your licensing, insurance, certifications, certificates, and more all in one spot.
      </p>

      <p className="text-gray-700 mb-4 text-lg sm:text-xl">
        <strong className="font-semibold text-black">Get notifications</strong> before licenses, insurance, and other certifications expire.
      </p>

      <p className="text-gray-700 mb-4 text-lg sm:text-xl">
        <strong className="font-semibold text-black">
          Employees share your{" "}
          <span className="text-black font-bold">
            Pro<span className="text-red-500">File</span>™
          </span>
        </strong>{" "}
        with clients and build trust and credibility at lightning speed.
      </p>

      <p className="text-gray-700 mb-4 text-lg sm:text-xl">
        <strong className="font-semibold text-black">Outrank your competition</strong> by showing clients the things that make you better and more qualified. They won't just need to take your word for it.
      </p>

      <p className="text-gray-700 mb-4 text-lg sm:text-xl">
        <strong className="font-semibold text-black">Let your Pro show like never before.</strong>
      </p>
    </div>
  </div>
</div>

<div className="mt-8 flex flex-col md:flex-row items-center justify-center gap-8 py-8">
  {/* Left Side - Image */}
  <div className="flex-shrink-0">
    <Image
      src="/images/p3.png"
      alt="Professional reviewing credentials"
      width={550}
      height={250}
      className="object-contain"
      priority
    />
  </div>
 
  {/* Right Side - Text */}
  <div className="max-w-lg text-center md:text-left">
  <h2 className="text-5xl font-semibold mb-6">
    Get <span className="text-red-500">free</span> leads.
  </h2>
 
  <p className="text-gray-600 text-2xl mb-4 text-justify">
    We don't use you for internet traffic and sell your leads to other people.  
    We care about our Pros and it shows. You get a notification anytime any verified client views your{" "}
    <span className="font-semibold text-black">
      Pro<span className="text-red-500">File</span>™
    </span>.
    Did we mention <span className="text-red-500">free </span>leads? You gotta love that.
  </p>
</div>
 
</div>
      {/* Final CTA */}
      <div className="bg-[#b6e3e9] py-12 px-4 text-center">
        <div className="flex flex-col items-center space-y-6">
          <h2 className="text-2xl sm:text-3xl font-semibold">
            Become a Profer Pro today
          </h2>
          <p className="text-gray-700 text-base sm:text-lg md:text-xl max-w-xl mx-auto mb-6">
            Join the only network that truly lets your caliber shine through to property owners.
          </p>
          <a
            href="#"
            className="inline-block bg-red-500 text-white text-xl sm:text-lg font-semibold px-6 sm:px-8 py-3 rounded-full shadow-md hover:bg-red-600 transition duration-300"
          >
            See Plans and Pricing
          </a>
        </div>
      </div>
    </>
  );
}
