import { ProsStepBusinessDetails } from "../../../../components/ProsArea/Prossteps/ProSecondStep";








export const metadata = {
  title: "Pros Step 2 | Profer",
  description: "Generated by create next app",
};




export default function Page(){

    return(<>
       
        <ProsStepBusinessDetails></ProsStepBusinessDetails>







    
    
    </>);
}