import Step2Client from "./Step2Client";


export const metadata = {
  title: "Pros Step 2 | Profer",
  description: "Generated by create next app",
};

export default function Page() {
  return <Step2Client />;
}
