import { ProjectAuction } from "@/components/Frontend/ProjectAuction/ProjectAuction";
import { Metadata } from "next";



export const metadata: Metadata = {
  title: "Project Auction | Profer",
  description: "Generated by create next app",
};



export default function ProjectAuc(){


    return(<>
    
        <ProjectAuction></ProjectAuction>
    
    
    </>);
}