
import ProjectSubmit from "@/components/Frontend/ProjectSubmissionFromUser/ProjectSubmit";
import { Metadata } from "next";





export const metadata: Metadata = {
  title: "Submit Project | Profer",
  description: "Generated by create next app",
};

export default function SubmitProjectPage() {
  return (
   <>
    <ProjectSubmit></ProjectSubmit>
   </>
  );
}