import { ProjectAuction } from "@/components/Frontend/ProjectAuction/ProjectAuction";



export const metadata = {
  title: "Project Auction | Profer",
  description: "Generated by create next app",
};

export default function ProjectAuc() {
  return (
    <>
      <ProjectAuction />
    </>
  );
}
